language: python
python:
    - "3.7"

# Initial set up
before_install:
    - sudo /etc/init.d/postgresql stop
    - sudo /etc/init.d/postgresql start 9.6

before_script:
    - psql -c 'create database nqueens;' -U postgres
    - psql -c 'create user challenge with encrypted password 'challenge';' -U postgres
    - psql -c 'grant all privileges on database nqueens to challenge;' -U postgres

# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - pytest

# DB configuration
services:
    - postgresql

addons:
    postgresql: "9.6"
env:
    global:
        - PGPORT=54321
