version: '3'

services:
    app:
        build: .
        command: python nqueens.py -i 4
        links:
            - db
    db:
        image: postgres:9.6
        container_name: my_postgres
        environment:
            - POSTGRES_USER=challenge
            - POSTGRES_PASSWORD=challenge
            - POSTGRES_DB=nqueens
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    postgres_data:
